repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        - id: end-of-file-fixer
        - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort  # sorts python imports
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black  # code formatting
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8  # code style
    rev: 4.0.1
    hooks:
      - id: flake8
